### PR TITLE
K8s

### PR DESCRIPTION
**Pull request by joshuansu0897**
### Not merge yet

this module have two problem to solve

One of them is below. That one happen when terraform try to deploy **chat-k8s module**
```
Error: Post "https://1230AFB0A7D8348EBEDDF385E7C13E94.gr7.us-east-1.eks.amazonaws.com/api/v1/namespaces": dial tcp 107.22.16.99:443: i/o timeout

  on ../../modules/chat-k8s/namespaces.tf line 1, in resource "kubernetes_namespace" "appchat":
   1: resource "kubernetes_namespace" "appchat" {
```

The second problem happen when you try to create nodes with **eks module** (files related **nodes.tf** and **role_nodes.tf**) (if you run **eks module** without **nodes.tf** and **role_nodes.tf** can create a eks cluster)
```
Error: error waiting for EKS Node Group (dev-cluster:dev-nodes) creation: AccessDenied: User: arn:aws:sts::xxxxxxxxxxx:assumed-role/AWSWesleyInstanceSetOpera-InstanceSetRequestMapper-UHMP15SVAEH9/prod-iso-c01-EgressShallowValidatorLambda is not authorized to perform: sts:AssumeRole on resource: arn:aws:iam::xxxxxxxxxxxxx:role/aws-service-role/eks-nodegroup.amazonaws.com/AWSServiceRoleForAmazonEKSNodegroup. Resource IDs: []

  on ../../modules/eks/nodes.tf line 1, in resource "aws_eks_node_group" "node":
   1: resource "aws_eks_node_group" "node" {
```

I will continue tomorrow

### CODE REVIEW

**Comment by joshuansu0897** [comment]
@jrsalgado Do you have any idea where is the problem? if not don't worries, i will solve that, but if you know something, you can save me time

**Comment by jrsalgado** [comment]
I created EKS modules will take this branch and edit this to use the current develop changes

**Comment by jrsalgado** [comment]
seems you dont have access to 107.22.16.99:443, the EKS cluster IP address

**Comment by jrsalgado** [comment]
- Merged develop, will keep working on service-k8s (the chat app) platform (level).
- Now testing the microservices can be mounted on eks

**Review by jrsalgado — APPROVED** [review]

**Pull request merged**
